language: php

php:
  - 7.4
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

env:
  - TESTBENCH_VERSION=3.8.* STABILITY=stable
  - TESTBENCH_VERSION=4.* STABILITY=stable
  - TESTBENCH_VERSION=5.* STABILITY=stable
  - TESTBENCH_VERSION=6.* STABILITY=stable

matrix:

  allow_failures:
    - php: nightly
  fast_finish: true

before_script:
  - travis_retry composer self-update
  - composer config minimum-stability ${STABILITY}
  - travis_retry composer require "orchestra/testbench:${TESTBENCH_VERSION}" --no-update
  - travis_retry composer update --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
