language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

env:
  - TESTBENCH_VERSION=3.5.*
  - TESTBENCH_VERSION=3.6.*
  - TESTBENCH_VERSION=dev-master

matrix:
  exclude:
    - php: 7.0
      env: TESTBENCH_VERSION=3.6.*
  allow_failures:
    - env: TESTBENCH_VERSION=dev-master
    - php: nightly
  fast_finish: true

before_script:
  - travis_retry composer self-update
  - travis_retry composer require "orchestra/testbench:${TESTBENCH_VERSION}" --no-update
  - travis_retry composer update --no-interaction --prefer-source

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover